version: '2'
services:
    web:
        build: ./web_client
        image: web_client_img
        container_name: web_client
        ports:
            - "8001:8000"
        volumes:
            - $PWD/web_client/src:/usr/src/app/src
        depends_on:
            - api

    api:
        build: ./api
        image: api_img
        container_name: api
        ports:
            - "8081:8080"
        volumes:
            - $PWD/api/src:/usr/src/app/src
        depends_on:
            - db

    db:
        build: ./mongo_db
        image: mongo_img
        container_name: mongo_db
        ports:
            - "27117:27017"
            - "28117:28017"
        env_file: ./default.env
